name: Close wontfix issues

on:
  issues:
    types:
      - labeled

jobs:
  close:
    if: github.event.label.name == 'wontfix'
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d '{"state":"closed"}'